package com.woniu.model;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.provinceid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityname
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String cityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityid
     *
     * @return the value of city.cityid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityid
     *
     * @param cityid the value for city.cityid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.provinceid
     *
     * @return the value of city.provinceid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.provinceid
     *
     * @param provinceid the value for city.provinceid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityname
     *
     * @return the value of city.cityname
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityname
     *
     * @param cityname the value for city.cityname
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }
}