package com.woniu.model;

public class Collect extends CollectKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.isdelete
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.isdelete
     *
     * @return the value of collect.isdelete
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.isdelete
     *
     * @param isdelete the value for collect.isdelete
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}