package com.woniu.model;

public class CollectKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.parkid
     *
     * @mbggenerated Fri Jul 19 16:14:05 CST 2019
     */
    private String parkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.userid
     *
     * @mbggenerated Fri Jul 19 16:14:05 CST 2019
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.parkid
     *
     * @return the value of collect.parkid
     *
     * @mbggenerated Fri Jul 19 16:14:05 CST 2019
     */
    public String getParkid() {
        return parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.parkid
     *
     * @param parkid the value for collect.parkid
     *
     * @mbggenerated Fri Jul 19 16:14:05 CST 2019
     */
    public void setParkid(String parkid) {
        this.parkid = parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.userid
     *
     * @return the value of collect.userid
     *
     * @mbggenerated Fri Jul 19 16:14:05 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.userid
     *
     * @param userid the value for collect.userid
     *
     * @mbggenerated Fri Jul 19 16:14:05 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}