package com.woniu.model;

public class CollectKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.parkid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer parkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.parkid
     *
     * @return the value of collect.parkid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getParkid() {
        return parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.parkid
     *
     * @param parkid the value for collect.parkid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setParkid(Integer parkid) {
        this.parkid = parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.userid
     *
     * @return the value of collect.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.userid
     *
     * @param userid the value for collect.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}