package com.woniu.model;

import java.util.Date;

public class Complain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.complainid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer complainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.complaintime
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Date complaintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.complaincontent
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private String complaincontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.replytime
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Date replytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.replycontent
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private String replycontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.isdelete
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.complainid
     *
     * @return the value of complain.complainid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getComplainid() {
        return complainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.complainid
     *
     * @param complainid the value for complain.complainid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setComplainid(Integer complainid) {
        this.complainid = complainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.userid
     *
     * @return the value of complain.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.userid
     *
     * @param userid the value for complain.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.complaintime
     *
     * @return the value of complain.complaintime
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Date getComplaintime() {
        return complaintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.complaintime
     *
     * @param complaintime the value for complain.complaintime
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setComplaintime(Date complaintime) {
        this.complaintime = complaintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.complaincontent
     *
     * @return the value of complain.complaincontent
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public String getComplaincontent() {
        return complaincontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.complaincontent
     *
     * @param complaincontent the value for complain.complaincontent
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setComplaincontent(String complaincontent) {
        this.complaincontent = complaincontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.replytime
     *
     * @return the value of complain.replytime
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.replytime
     *
     * @param replytime the value for complain.replytime
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.replycontent
     *
     * @return the value of complain.replycontent
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.replycontent
     *
     * @param replycontent the value for complain.replycontent
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.isdelete
     *
     * @return the value of complain.isdelete
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.isdelete
     *
     * @param isdelete the value for complain.isdelete
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}