package com.woniu.model;

import java.util.Date;

public class Invoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invioceid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Integer invioceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.userid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.applytime
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.taxpayersnum
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private String taxpayersnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.companyaddress
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private String companyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.bankaccount
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private String bankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.money
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.createtime
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.isdelete
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invioceid
     *
     * @return the value of invoice.invioceid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Integer getInvioceid() {
        return invioceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invioceid
     *
     * @param invioceid the value for invoice.invioceid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setInvioceid(Integer invioceid) {
        this.invioceid = invioceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.userid
     *
     * @return the value of invoice.userid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.userid
     *
     * @param userid the value for invoice.userid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.applytime
     *
     * @return the value of invoice.applytime
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.applytime
     *
     * @param applytime the value for invoice.applytime
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.taxpayersnum
     *
     * @return the value of invoice.taxpayersnum
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public String getTaxpayersnum() {
        return taxpayersnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.taxpayersnum
     *
     * @param taxpayersnum the value for invoice.taxpayersnum
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setTaxpayersnum(String taxpayersnum) {
        this.taxpayersnum = taxpayersnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.companyaddress
     *
     * @return the value of invoice.companyaddress
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.companyaddress
     *
     * @param companyaddress the value for invoice.companyaddress
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.bankaccount
     *
     * @return the value of invoice.bankaccount
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.bankaccount
     *
     * @param bankaccount the value for invoice.bankaccount
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.money
     *
     * @return the value of invoice.money
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.money
     *
     * @param money the value for invoice.money
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.createtime
     *
     * @return the value of invoice.createtime
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.createtime
     *
     * @param createtime the value for invoice.createtime
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.isdelete
     *
     * @return the value of invoice.isdelete
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.isdelete
     *
     * @param isdelete the value for invoice.isdelete
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}