package com.woniu.model;

public class Park {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.parkid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer parkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.propertyid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Integer propertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.parkfloor
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private String parkfloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.parknum
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private String parknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.isstatus
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Boolean isstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.isavailable
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Boolean isavailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.parkinfo
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private String parkinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park.isdelete
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.parkid
     *
     * @return the value of park.parkid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getParkid() {
        return parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.parkid
     *
     * @param parkid the value for park.parkid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setParkid(Integer parkid) {
        this.parkid = parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.userid
     *
     * @return the value of park.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.userid
     *
     * @param userid the value for park.userid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.propertyid
     *
     * @return the value of park.propertyid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Integer getPropertyid() {
        return propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.propertyid
     *
     * @param propertyid the value for park.propertyid
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setPropertyid(Integer propertyid) {
        this.propertyid = propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.parkfloor
     *
     * @return the value of park.parkfloor
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public String getParkfloor() {
        return parkfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.parkfloor
     *
     * @param parkfloor the value for park.parkfloor
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setParkfloor(String parkfloor) {
        this.parkfloor = parkfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.parknum
     *
     * @return the value of park.parknum
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public String getParknum() {
        return parknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.parknum
     *
     * @param parknum the value for park.parknum
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setParknum(String parknum) {
        this.parknum = parknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.isstatus
     *
     * @return the value of park.isstatus
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Boolean getIsstatus() {
        return isstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.isstatus
     *
     * @param isstatus the value for park.isstatus
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setIsstatus(Boolean isstatus) {
        this.isstatus = isstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.isavailable
     *
     * @return the value of park.isavailable
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Boolean getIsavailable() {
        return isavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.isavailable
     *
     * @param isavailable the value for park.isavailable
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setIsavailable(Boolean isavailable) {
        this.isavailable = isavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.parkinfo
     *
     * @return the value of park.parkinfo
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public String getParkinfo() {
        return parkinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.parkinfo
     *
     * @param parkinfo the value for park.parkinfo
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setParkinfo(String parkinfo) {
        this.parkinfo = parkinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park.isdelete
     *
     * @return the value of park.isdelete
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park.isdelete
     *
     * @param isdelete the value for park.isdelete
     *
     * @mbggenerated Wed Jul 17 20:24:16 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}