package com.woniu.model;

import java.util.Date;

public class Porder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.orderid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.parkid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String parkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.carid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String carid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.userid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.singleprice
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Double singleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.ocreatetime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Date ocreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.ostarttime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Date ostarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.oendtime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Date oendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.totalprice
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Double totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.iscompleted
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Boolean iscompleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column porder.isfinish
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Boolean isfinish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.orderid
     *
     * @return the value of porder.orderid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.orderid
     *
     * @param orderid the value for porder.orderid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.parkid
     *
     * @return the value of porder.parkid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getParkid() {
        return parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.parkid
     *
     * @param parkid the value for porder.parkid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setParkid(String parkid) {
        this.parkid = parkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.carid
     *
     * @return the value of porder.carid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.carid
     *
     * @param carid the value for porder.carid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setCarid(String carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.userid
     *
     * @return the value of porder.userid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.userid
     *
     * @param userid the value for porder.userid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.singleprice
     *
     * @return the value of porder.singleprice
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Double getSingleprice() {
        return singleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.singleprice
     *
     * @param singleprice the value for porder.singleprice
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setSingleprice(Double singleprice) {
        this.singleprice = singleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.ocreatetime
     *
     * @return the value of porder.ocreatetime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Date getOcreatetime() {
        return ocreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.ocreatetime
     *
     * @param ocreatetime the value for porder.ocreatetime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setOcreatetime(Date ocreatetime) {
        this.ocreatetime = ocreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.ostarttime
     *
     * @return the value of porder.ostarttime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Date getOstarttime() {
        return ostarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.ostarttime
     *
     * @param ostarttime the value for porder.ostarttime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setOstarttime(Date ostarttime) {
        this.ostarttime = ostarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.oendtime
     *
     * @return the value of porder.oendtime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Date getOendtime() {
        return oendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.oendtime
     *
     * @param oendtime the value for porder.oendtime
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setOendtime(Date oendtime) {
        this.oendtime = oendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.totalprice
     *
     * @return the value of porder.totalprice
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Double getTotalprice() {
        return (new Date().getTime() - ostarttime.getTime())/1000/60/60*singleprice;
        
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.totalprice
     *
     * @param totalprice the value for porder.totalprice
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.iscompleted
     *
     * @return the value of porder.iscompleted
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Boolean getIscompleted() {
        return iscompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.iscompleted
     *
     * @param iscompleted the value for porder.iscompleted
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setIscompleted(Boolean iscompleted) {
        this.iscompleted = iscompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column porder.isfinish
     *
     * @return the value of porder.isfinish
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Boolean getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column porder.isfinish
     *
     * @param isfinish the value for porder.isfinish
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setIsfinish(Boolean isfinish) {
        this.isfinish = isfinish;
    }
}