package com.woniu.model;

public class Property {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.propertyid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String propertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.propertyname
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String propertyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.userid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.provinceid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.zoneid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String zoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.cityid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.fulladdress
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String fulladdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.proportion
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Integer proportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.pearnings
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Double pearnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.propertyphone
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private String propertyphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.isdelete
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.propertyid
     *
     * @return the value of property.propertyid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getPropertyid() {
        return propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.propertyid
     *
     * @param propertyid the value for property.propertyid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setPropertyid(String propertyid) {
        this.propertyid = propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.propertyname
     *
     * @return the value of property.propertyname
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getPropertyname() {
        return propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.propertyname
     *
     * @param propertyname the value for property.propertyname
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setPropertyname(String propertyname) {
        this.propertyname = propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.userid
     *
     * @return the value of property.userid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.userid
     *
     * @param userid the value for property.userid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.provinceid
     *
     * @return the value of property.provinceid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.provinceid
     *
     * @param provinceid the value for property.provinceid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.zoneid
     *
     * @return the value of property.zoneid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getZoneid() {
        return zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.zoneid
     *
     * @param zoneid the value for property.zoneid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setZoneid(String zoneid) {
        this.zoneid = zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.cityid
     *
     * @return the value of property.cityid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.cityid
     *
     * @param cityid the value for property.cityid
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.fulladdress
     *
     * @return the value of property.fulladdress
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getFulladdress() {
        return fulladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.fulladdress
     *
     * @param fulladdress the value for property.fulladdress
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.proportion
     *
     * @return the value of property.proportion
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Integer getProportion() {
        return proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.proportion
     *
     * @param proportion the value for property.proportion
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setProportion(Integer proportion) {
        this.proportion = proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.pearnings
     *
     * @return the value of property.pearnings
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Double getPearnings() {
        return pearnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.pearnings
     *
     * @param pearnings the value for property.pearnings
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setPearnings(Double pearnings) {
        this.pearnings = pearnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.propertyphone
     *
     * @return the value of property.propertyphone
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public String getPropertyphone() {
        return propertyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.propertyphone
     *
     * @param propertyphone the value for property.propertyphone
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setPropertyphone(String propertyphone) {
        this.propertyphone = propertyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.isdelete
     *
     * @return the value of property.isdelete
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.isdelete
     *
     * @param isdelete the value for property.isdelete
     *
     * @mbggenerated Mon Jul 22 16:47:55 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}