package com.woniu.model;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.provinceid
     *
     * @mbggenerated Mon Jul 22 16:38:43 CST 2019
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pname
     *
     * @mbggenerated Mon Jul 22 16:38:43 CST 2019
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.provinceid
     *
     * @return the value of province.provinceid
     *
     * @mbggenerated Mon Jul 22 16:38:43 CST 2019
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.provinceid
     *
     * @param provinceid the value for province.provinceid
     *
     * @mbggenerated Mon Jul 22 16:38:43 CST 2019
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pname
     *
     * @return the value of province.pname
     *
     * @mbggenerated Mon Jul 22 16:38:43 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pname
     *
     * @param pname the value for province.pname
     *
     * @mbggenerated Mon Jul 22 16:38:43 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}