package com.woniu.model;

public class Tree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.id
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.tre_id
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Integer treId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.pid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.NAME
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.FILE
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.icon
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.id
     *
     * @return the value of tree.id
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.id
     *
     * @param id the value for tree.id
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.tre_id
     *
     * @return the value of tree.tre_id
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Integer getTreId() {
        return treId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.tre_id
     *
     * @param treId the value for tree.tre_id
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setTreId(Integer treId) {
        this.treId = treId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.pid
     *
     * @return the value of tree.pid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.pid
     *
     * @param pid the value for tree.pid
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.NAME
     *
     * @return the value of tree.NAME
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.NAME
     *
     * @param name the value for tree.NAME
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.FILE
     *
     * @return the value of tree.FILE
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.FILE
     *
     * @param file the value for tree.FILE
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setFile(String file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.icon
     *
     * @return the value of tree.icon
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.icon
     *
     * @param icon the value for tree.icon
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}