package com.woniu.model;

public class UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.roleid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.userid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.roleid
     *
     * @return the value of user_role.roleid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.roleid
     *
     * @param roleid the value for user_role.roleid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.userid
     *
     * @return the value of user_role.userid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.userid
     *
     * @param userid the value for user_role.userid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}