package com.woniu.model;

import java.util.Date;
import java.util.List;

import org.springframework.validation.annotation.Validated;

public class User {
	
	
	@Override
	public String toString() {
		return "User [roles=" + roles + ", trees=" + trees + ", userid=" + userid + ", userphone=" + userphone
				+ ", userpass=" + userpass + ", birthday=" + birthday + ", username=" + username + ", usersex="
				+ usersex + ", useraddress=" + useraddress + ", userphoto=" + userphoto + ", uearnings=" + uearnings
				+ ", ubalance=" + ubalance + ", createtime=" + createtime + ", isdelete=" + isdelete + "]";
	}

	private List roles;
	private List trees;
    public List getRoles() {
		return roles;
	}

	public void setRoles(List roles) {
		this.roles = roles;
	}

	public List getTrees() {
		return trees;
	}

	public void setTrees(List trees) {
		this.trees = trees;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userphone
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userpass
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String userpass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usersex
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Boolean usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.useraddress
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String useraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userphoto
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uearnings
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Double uearnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ubalance
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Double ubalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createtime
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isdelete
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userphone
     *
     * @return the value of user.userphone
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userphone
     *
     * @param userphone the value for user.userphone
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userpass
     *
     * @return the value of user.userpass
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getUserpass() {
        return userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userpass
     *
     * @param userpass the value for user.userpass
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usersex
     *
     * @return the value of user.usersex
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Boolean getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usersex
     *
     * @param usersex the value for user.usersex
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUsersex(Boolean usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.useraddress
     *
     * @return the value of user.useraddress
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.useraddress
     *
     * @param useraddress the value for user.useraddress
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userphoto
     *
     * @return the value of user.userphoto
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userphoto
     *
     * @param userphoto the value for user.userphoto
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uearnings
     *
     * @return the value of user.uearnings
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Double getUearnings() {
        return uearnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uearnings
     *
     * @param uearnings the value for user.uearnings
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUearnings(Double uearnings) {
        this.uearnings = uearnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ubalance
     *
     * @return the value of user.ubalance
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Double getUbalance() {
        return ubalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ubalance
     *
     * @param ubalance the value for user.ubalance
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setUbalance(Double ubalance) {
        this.ubalance = ubalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createtime
     *
     * @return the value of user.createtime
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createtime
     *
     * @param createtime the value for user.createtime
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isdelete
     *
     * @return the value of user.isdelete
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isdelete
     *
     * @param isdelete the value for user.isdelete
     *
     * @mbggenerated Thu Jul 18 16:44:42 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}