package com.woniu.model;

public class Zone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zoneid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    private Integer zoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zonename
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    private String zonename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zoneid
     *
     * @return the value of zone.zoneid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public Integer getZoneid() {
        return zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zoneid
     *
     * @param zoneid the value for zone.zoneid
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public void setZoneid(Integer zoneid) {
        this.zoneid = zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zonename
     *
     * @return the value of zone.zonename
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public String getZonename() {
        return zonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zonename
     *
     * @param zonename the value for zone.zonename
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    public void setZonename(String zonename) {
        this.zonename = zonename;
    }
}