package com.woniu.mapper;

import com.woniu.model.CollectExample;
import com.woniu.model.CollectKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int countByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int deleteByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int deleteByPrimaryKey(CollectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int insert(CollectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int insertSelective(CollectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    List<CollectKey> selectByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CollectKey record, @Param("example") CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Wed Jul 17 17:04:30 CST 2019
     */
    int updateByExample(@Param("record") CollectKey record, @Param("example") CollectExample example);
}