package com.woniu.mapper;

import com.woniu.model.Park;
import com.woniu.model.ParkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int countByExample(ParkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int deleteByExample(ParkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int deleteByPrimaryKey(String parkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int insert(Park record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int insertSelective(Park record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    List<Park> selectByExample(ParkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    Park selectByPrimaryKey(String parkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Park record, @Param("example") ParkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int updateByExample(@Param("record") Park record, @Param("example") ParkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int updateByPrimaryKeySelective(Park record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbggenerated Thu Jul 18 16:02:22 CST 2019
     */
    int updateByPrimaryKey(Park record);
}