server:
  port: 9000
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xawn.f3322.net:3306/db7?characterEncoding=utf8
    username: db7
    password: 76575656!
  mvc:
    view:
      prefix: /
      suffix: .jsp
   
logging:
  level:
    com: 
      woniu: 
        mapper: DEBUG
