server:
  port: 9000
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.9.212:3306/sharepark?characterEncoding=utf8
    username: root
    password: 
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
logging:
  level:
    com: 
      woniu: 
        mapper: DEBUG
